server:
  port: 8500
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka, http://localhost:8802/eureka
spring:
  application:
    name: gateway
  cloud:
    gateway:
      #      http://localhost:8500/borrow/** -> http://localhost:8280/borrow/**
      server:
        webflux:
          # 配置路由，注意这里是个列表，每一项都包含了很多信息
          routes:
            - id: borrow-service # 路由名称
              uri: lb://borrowservice # 路由的地址，lb表示使用负载均衡到微服务，也可以使用http正常转发
              predicates: # 路由规则，断言什么请求会被路由
                - Path=/borrow/**
            - id: book-service
              uri: lb://bookservice
              predicates:
                - Path=/book/**
              filters: # 添加过滤器
                - AddRequestHeader=Test, HelloWorld!
              # AddRequestHeader 就是添加请求头信息，其他工厂请查阅官网
