server:
  port: 8280
spring:
  application:
    name: borrow-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudstudy?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址
        server-addr: localhost:8848
        namespace: 82c88e75-1b7f-4fef-a96f-e5acc2bd4938
        ephemeral: false
        cluster-name: Chengdu
    loadbalancer:
      nacos:
        enabled: true

