spring:
  application:
    name: user-service
  config:
    import: nacos:user-service-dev.yml          # 替代 bootstrap.yml
  profiles:
    # 环境也是和配置文件保持一致
    active: dev
  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址
        server-addr: localhost:8848
        namespace: 273e2e6d-01c6-4538-b419-dd016ed4834f
      config:
        server-addr: localhost:8848
        namespace: 273e2e6d-01c6-4538-b419-dd016ed4834f
        group: DEFAULT_GROUP
seata:
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace: 273e2e6d-01c6-4538-b419-dd016ed4834f
      dataId: seataServer.properties
      username: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace: 273e2e6d-01c6-4538-b419-dd016ed4834f
      username: nacos
      password: nacos


